image: python:3.5

stages:
  - build
  - tests

do build:
  stage: build
  tags:
    - commonpf
    - build
    - python3
  script:
    - pip3 install -r requirements.txt
    - pip3 install -e .

do tests:
  stage: tests
  tags:
    - commonpf
    - tests
    - python3
  script:
    - pytest tests
