image: python:3.5

before_script:
  - pip3 install -r requirements.txt
  - pip3 install -e .

run tests:
  only:
    - master
  tags:
    - commonpf
    - python3
    - tests
  script:
    - pytest tests
  coverage: '/TOTAL.*\s+(\d+%)$/'
