image: localhost:5000/ubuntu-pytests:3.5

before_script:
  - pip3 install -r requirements.txt
  - pip3 install -e .
  - pip3 show myapp

run tests:
  only:
    - master
  tags:
    - python3
    - tests
  script:
    - pytest tests
  coverage: '/TOTAL.*\s+(\d+%)$/'
