image: python:3.5

before_script:
  - pip3 install -r requirements.txt
  - pip3 install -e .

run tests on app:
  except:
    changes:
      - .gitignore
      - README.md
      - docs/*
  tags:
    - commonpf
    - tests
    - python3
  script:
    - pytest tests
